### ISSUE TITLE
CSS issue. Submenu's are not displayed correctly in the main menu.

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#11]
I use sub-menu's on my Chapter site on my main menu. They don't seem to be displayed properly.

See attached image.

![image](https://user-images.githubusercontent.com/5627431/56447275-9e1afb00-6307-11e9-9a6c-dcae6fa69dcb.png)

**Comment by hugosolar** [comment]
fixed in 1e2e3df
