### ISSUE TITLE
News Archive page needs a proper design

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#12]
I assume that a lot of chapter site rely on posts within their template. Currently there is no proper design for an overview of posts (archive page). 

We need a properly designed archive page. See https://nl-beta.creativecommons.org/nieuws/

**Comment by hugosolar** [comment]
Commit fff1321
- Add proper style to archive.php and category.php
- Add template-page.php in order to use it with pages as a custom /news archive

**Comment by mzeinstra** [comment]
The solution makes it a page template. Wordpress offers a feature to set a specific page as the post archive. Mine does not show any changes.
![image](https://user-images.githubusercontent.com/5627431/56884645-b529bd80-6a6a-11e9-9e41-a2a881d85e6b.png)

See: https://nl-beta.creativecommons.org/nieuws/

**Comment by hugosolar** [comment]
Fixed in b1d99f1
