### ISSUE TITLE
Where can I change the copyright notice in the footer?

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#15]
I want to customise the copyright notice in the footer on my chapter site, translate it to Dutch.  

How can I do that?

**Comment by hugosolar** [comment]
Added a footer content field to the site settings (78185f3)
<img width="719" alt="Screen Shot 2019-04-27 at 12 27 09 PM" src="https://user-images.githubusercontent.com/894708/56852316-d01ff480-68e7-11e9-8227-4fdb3d17f0d9.png">
