### ISSUE TITLE
Search on chapter sites do not work yet – no search page implemented

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#16]
The new archive page allows users to search through the posts, however there is no search page available yet.

See: https://nl-beta.creativecommons.org/?search=Open+Access

**Comment by hugosolar** [comment]
The wordpress default search works with the `s` parameter
the search you refer should be like this
https://nl-beta.creativecommons.org/?s=Open+Access
I use the `search` parameter only in the post archive to avoid conflicts with the default wordpress search
does that make sense to you?

**Comment by mzeinstra** [comment]
Makes sense to me.

When I usesd the ?search  query I did not find anything. Now I do.

However this is not implemented throughout. 

Compare:
https://nl-beta.creativecommons.org/news-temp/ (page template)
with
https://nl-beta.creativecommons.org/nieuws/ build in 'post page'

the latter has no search, the former has.

Maybe I am misusing the issue now :)

**Comment by hugosolar** [comment]
haha don't worry. 
I added the filter to the 'post page' in 72dffa4
