### ISSUE TITLE
Feature request: CCSearch plugin for the homepage

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#17]
I'd like to have a full width way to link my users to ccsearch. Preferably I'd like to have CCSearch integrated in the template.

I've now tried to use the custom text widget to make a full width reference to the CCSearch but that is not really pretty. See: https://nl-beta.creativecommons.org/ and attached screenshot.

![image](https://user-images.githubusercontent.com/5627431/56949300-d3f38700-6b32-11e9-8a11-cefddf35c4fe.png)

Can we have this full width widget or is there another elegant solution for this?

**Comment by mzeinstra** [comment]
I made a quick mock-up of of what I would expect:

![image](https://user-images.githubusercontent.com/5627431/56950065-d9ea6780-6b34-11e9-8005-eee22ae1705b.png)

**Comment by kgodey** [comment]
I recommend using the CC Search plugin by the Greek School Network: https://wordpress.org/plugins/ls-wp-ccsearch/
