### ISSUE TITLE
Feature request: Create or add plugin that optimises ease of attribution

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#18]
there have been good plugins that allow ease of attribution for Wordpress that are visibly pleasing as well.

Example https://www.kl.nl/nieuws/chapter-creative-commons-nederland-opgericht/
Hover over the 'i' icon on the image to see proper attreibution of the image.

It would be good that all chapter sites have this ease of attribution.

**Comment by kgodey** [comment]
This should be solved by our WordPress plugin. https://github.com/creativecommons/wp-plugin-creativecommons

**Comment by kgodey** [comment]
On WordPress.org: https://wordpress.org/plugins/creative-commons/
