### ISSUE TITLE
Feature request: Import Markdown plugin

### ISSUE THREAD

**Issue by riouwa** [creativecommons/wp-theme-cc-chapter#26]
CC Indonesia website were once hosted here: http://creativecommons.or.id/ and all of its posts were written as a markdown file. As we are moving out to wordpress, we would like an easier way to import all of the previous posts into new wordpress site.

Therefore we would like https://wordpress.org/plugins/import-markdown/ implemented so that we could import all of the markdown file into the new site

**Comment by CreativeCommonsIndonesia** [comment]
Hello, yes, I think we need that plugin to be installed to move our previous contents to the new website. Rio here is one of Wikimedia Indonesia's staff who is helping us with the website migration.

Thank you.
Hilman Fathoni-CC Indonesia

**Comment by hugosolar** [comment]
Plugin available in production site
