### ISSUE TITLE
Is this a child-theme?

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/wp-theme-cc-chapter#8]
I read on style.css that the theme is a child theme of 'twentysixteen'. If not we must remove that from the style.css or have unforeseen, and difficult to debug consequences.

> `Template: twentysixteen`

**Comment by hugosolar** [comment]
We're planning to remove that dependency in the future. 
I added to the pending features issues #7

**Comment by kgodey** [comment]
Closing this since it's tracked in #7.
